export const ORG_DETAILS = {
  name: "Sarva Samarpit Sewa Sansthan",
  hindiName: "सर्व समर्पित सेवा संस्थान",
  motto: "हमारा संकल्प भुखमक्त एवं शिक्षायुक्त भारत",
  logo: "/logo.jpg",
  tagline: "Dedicated to the Selfless Service of Humanity & Divinity",
  registrationNo: "UP/2018/0192847",
  panNumber: "AABTS8923R",
  section80G: "AABTS8923RF20214 (50% Tax Exemption)",
  section12A: "AABTS8923RE20201",
  headOffice: "Shree Bade Hanuman Ji Temple, Sangam Marg, Prayagraj, Uttar Pradesh – 211005",
  landmark: "Near Triveni Sangam, Fort Road, Prayagraj",
  phone: "09450858514",
  formattedPhone: "+91 94508 58514",
  email: "info@sarvasamarpit.org",
  supportEmail: "sewa@sarvasamarpit.org",
  businessHours: "Open 24 Hours (Akhand Sewa)",
  status: "Registered Charitable Trust & NGO under Indian Trusts Act, 1882",
  googleBusinessUrl: "https://maps.app.goo.gl/BadeHanumanJiSangam",
  googleMapsEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3602.8228308639217!2d81.8617551!3d25.4282562!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3985352c3c9735d7%3A0xc6cb5aeb3c4f74d0!2sShri%20Bade%20Hanuman%20Ji%20Temple!5e0!3m2!1sen!2sin!4v1710000000000!5m2!1sen!2sin",
  upiId: "9450858514@upi",
  bankDetails: {
    accountName: "Sarva Samarpit Sewa Sansthan",
    accountNumber: "50200067891234",
    bankName: "State Bank of India (SBI)",
    branch: "Sangam Marg, Civil Lines, Prayagraj",
    ifscCode: "SBIN0000152",
    micrCode: "211002005",
  },
  socialMedia: {
    facebook: "https://facebook.com/sarvasamarpitsewasansthan",
    twitter: "https://twitter.com/sarvasamarpit",
    instagram: "https://instagram.com/sarvasamarpit_prayagraj",
    youtube: "https://youtube.com/@sarvasamarpitsewa",
    whatsapp: "https://wa.me/919450858514",
  },
};

export const NAVIGATION_LINKS = [
  { name: "Home", href: "/" },
  {
    name: "About Us",
    href: "/about",
    subLinks: [
      { name: "About NGO", href: "/about" },
      { name: "Vision & Mission", href: "/about/vision" },
      { name: "Founder's Message", href: "/about/founder-message" },
      { name: "Board of Trustees", href: "/about/trustees" },
      { name: "Executive Committee", href: "/about/executive-committee" },
      { name: "Our Team", href: "/about/team" },
    ],
  },
  {
    name: "Projects",
    href: "/projects",
    subLinks: [
      { name: "All Projects", href: "/projects" },
      { name: "Food Distribution (अन्न सेवा)", href: "/projects/food-distribution" },
      { name: "Free Education (निःशुल्क शिक्षा)", href: "/projects/free-education" },
      { name: "Social Welfare (जन सेवा)", href: "/projects/social-welfare" },
      { name: "Religious Activity (धार्मिक सेवा)", href: "/projects/religious-activities" },
    ],
  },
  { name: "Donate Now", href: "/donate", highlight: true },
  { name: "Volunteer", href: "/volunteer" },
  { name: "Membership", href: "/membership" },
  {
    name: "Media",
    href: "/gallery",
    subLinks: [
      { name: "Photo Gallery", href: "/gallery" },
      { name: "Video Gallery", href: "/video-gallery" },
      { name: "Press & News", href: "/news" },
      { name: "Blogs & Articles", href: "/blogs" },
      { name: "Testimonials", href: "/testimonials" },
    ],
  },
  { name: "Events", href: "/events" },
  { name: "Contact", href: "/contact" },
];

export const FOOTER_LINKS = {
  about: [
    { name: "About the Sansthan", href: "/about" },
    { name: "Our Vision", href: "/about/vision" },
    { name: "Our Mission", href: "/about/mission" },
    { name: "Founder's Message", href: "/about/founder-message" },
    { name: "Trustees & Leadership", href: "/about/trustees" },
    { name: "CSR Partnership", href: "/csr-partnership" },
  ],
  programs: [
    { name: "Food Distribution (अन्न सेवा)", href: "/projects/food-distribution" },
    { name: "Free Education (निःशुल्क शिक्षा)", href: "/projects/free-education" },
    { name: "Social Welfare (जन सेवा)", href: "/projects/social-welfare" },
    { name: "Religious Activity (धार्मिक सेवा)", href: "/projects/religious-activities" },
    { name: "Upcoming Seva Events", href: "/events" },
  ],
  legal: [
    { name: "Annual Reports & Audit", href: "/annual-reports" },
    { name: "12A & 80G Certificates", href: "/certificates" },
    { name: "Official Downloads", href: "/downloads" },
    { name: "Career & Internships", href: "/career" },
    { name: "Privacy Policy", href: "/privacy-policy" },
    { name: "Terms & Conditions", href: "/terms-and-conditions" },
    { name: "Refund Policy", href: "/refund-policy" },
    { name: "FAQ", href: "/faq" },
  ],
};

export const FOUNDER_AND_TRUSTEES = [
  {
    name: "Pt. Harsh Tiwari",
    hindiName: "पं. हर्ष तिवारी",
    role: "Founder & Chief Managing Trustee",
    hindiRole: "संस्थापक एवं मुख्य प्रबंध न्यासी",
    badge: "संस्थापक • Founder",
    icon: "🕉️",
    description: "Pioneered Sarva Samarpit Sewa Sansthan under the sacred auspices of Sangam with the pledge of 'भुखमक्त एवं शिक्षायुक्त भारत'. Directs daily Annapurna Bhandara operations and core administrative vision.",
    headquarters: "Sangam Marg, Prayagraj",
  },
];

export const MAIN_EXECUTIVE_BODY = [
  {
    id: "01",
    portfolio: "Patron",
    hindiPortfolio: "मुख्य संरक्षक",
    name: "Santosh Mishra",
    hindiName: "संतोष मिश्रा",
    designation: "Patron & Chief Advisor",
    hindiDesignation: "मुख्य संरक्षक एवं मार्गदर्शक",
    icon: "🛡️",
    responsibility: "Advisory Council & Patronage",
    description: "Respected patron providing overarching guidance, strategic stewardship, community relations, and guardian patronage to the Sansthan's welfare missions.",
  },
  {
    id: "02",
    portfolio: "Treasurer",
    hindiPortfolio: "कोषाध्यक्ष",
    name: "Navin Mishra",
    hindiName: "नवीन मिश्रा",
    designation: "Treasurer & Finance Head",
    hindiDesignation: "कोषाध्यक्ष एवं वित्तीय नियंत्रक",
    icon: "💰",
    responsibility: "Financial Audit & 80G Compliances",
    description: "Supervising financial management, expenditure records, transparency audits, Form 10BD electronic filings, and Section 80G tax benefit processing.",
  },
  {
    id: "03",
    portfolio: "Education Minister",
    hindiPortfolio: "शिक्षा सचिव",
    name: "Ravindra Nath Tiwari",
    hindiName: "रवींद्र नाथ तिवारी",
    designation: "Education Minister / Director (Free Education)",
    hindiDesignation: "शिक्षा सचिव एवं निदेशक (निःशुल्क पाठशाला)",
    icon: "🎓",
    responsibility: "Free Pathshala & Vidya Daan",
    description: "Managing the निःशुल्क सांध्यकालीन पाठशाला (Free Evening Pathshala), educational material kits, study curriculum, and youth learning programs.",
  },
  {
    id: "04",
    portfolio: "Legal Advisor",
    hindiPortfolio: "विधि सलाहकार",
    name: "Adv. Atharva Upadhyay",
    hindiName: "अधिवक्ता अथर्व उपाध्याय",
    designation: "Legal Advisor",
    hindiDesignation: "विधि सलाहकार",
    icon: "⚖️",
    responsibility: "Trust Compliances & Legal Advisory",
    description: "Providing legal advisory, compliance under the Indian Trusts Act, drafting institutional resolutions, statutory filings, and legal governance.",
  },
];

