import React from "react";
import { PageHeader } from "@/components/common/PageHeader";
import { FileText, Download, ShieldCheck, CheckCircle2 } from "lucide-react";
import { ORG_DETAILS } from "@/lib/constants";

export const metadata = {
  title: "Annual Financial Reports & Audits | Sarva Samarpit Sewa Sansthan",
  description: "Download audited financial statements, annual activity reports, and Form 10BD filings for Sarva Samarpit Sewa Sansthan.",
};

const REPORTS = [
  {
    year: "FY 2025 - 2026",
    title: "Audited Annual Financial & Seva Report 2025-26",
    status: "Audited by CA Satish Kumar Agarwal & Associates",
    fileSize: "2.4 MB PDF",
  },
  {
    year: "FY 2024 - 2025",
    title: "Audited Annual Financial & Seva Report 2024-25",
    status: "Audited & Income Tax Form 10B/10BD Filed",
    fileSize: "2.1 MB PDF",
  },
  {
    year: "FY 2023 - 2024",
    title: "Audited Annual Financial & Seva Report 2023-24",
    status: "Audited & Income Tax Form 10B Filed",
    fileSize: "1.9 MB PDF",
  },
];

export default function AnnualReportsPage() {
  return (
    <div>
      <PageHeader
        title="Annual Reports &amp; Financial Audits"
        subtitle="Uncompromising financial transparency. Review audited statements of accounts, Form 10BD disclosures, and impact metrics."
        breadcrumbs={[{ label: "Annual Reports" }]}
        badge="100% Transparent Governance"
      />

      <div className="py-16 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto space-y-8">
        <div className="bg-orange-50/70 p-6 rounded-lg border border-orange-200 text-xs sm:text-sm text-gray-700 leading-relaxed">
          <strong className="text-gray-900 block mb-1">Statement of Stewardship:</strong>
          Sarva Samarpit Sewa Sansthan is committed to absolute fiscal probity. Every rupee donated by devotees is accounted for, reconciled with bank statements, audited by statutory chartered accountants, and reported annually to the Income Tax Department.
        </div>

        <div className="space-y-4">
          {REPORTS.map((r) => (
            <div
              key={r.year}
              className="p-6 bg-white rounded-lg border border-gray-200 shadow-xs hover:shadow-xs transition-all flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
            >
              <div className="flex items-start gap-4">
                <div className="p-3 rounded-lg bg-orange-100 text-ngo-orange shrink-0">
                  <FileText className="w-6 h-6" />
                </div>
                <div>
                  <span className="text-xs font-bold text-ngo-orange uppercase tracking-wider block">
                    {r.year}
                  </span>
                  <h4 className="font-heading font-semibold text-base text-gray-900 mt-0.5">
                    {r.title}
                  </h4>
                  <p className="text-xs text-gray-500 mt-1 flex items-center gap-1.5">
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                    <span>{r.status}</span>
                  </p>
                </div>
              </div>

              <a
                href={`#download-${r.year}`}
                onClick={(e) => {
                  e.preventDefault();
                  alert(`Downloading ${r.title} (${r.fileSize}). Generated by Sansthan Document System.`);
                }}
                className="px-5 py-2.5 rounded-md bg-ngo-dark hover:bg-black text-white text-xs font-bold flex items-center gap-2 shadow-sm transition-all shrink-0"
              >
                <Download className="w-3.5 h-3.5" /> Download PDF ({r.fileSize})
              </a>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
